changelog:
  # 新增：定义更新日志中每个提交条目的显示格式
  # $TITLE 代表提交信息的主题行，@$AUTHOR 代表提交者的 GitHub 用户名
  commit-template: '- $TITLE (@$AUTHOR)'

  # 1. 排除不希望显示在更新日志中的提交
  # 排除自动生成的 Merge 提交，以及维护性的 chore, ci, build, test 提交
  exclude:
    commits:
      - pattern: '^Merge'
      - pattern: '^chore'
      - pattern: '^ci'
      - pattern: '^build'
      - pattern: '^test'

  # 2. 核心分类规则
  categories:

    - title: ✨ 新增功能 (Features)
      # 匹配 'feat'
      commits:
        - pattern: '^feat'

    - title: 🐛 Bug 修复 (Bug Fixes)
      # 匹配 'fix'
      commits:
        - pattern: '^fix'

    - title: 🚀 性能与代码改进 (Improvements)
      # 匹配 'perf'、'refactor' 和 'style'
      commits:
        # 使用 OR 逻辑 (|) 将多个前缀合并到一行
        - pattern: '^perf|^refactor|^style'

    - title: 📚 文档更新 (Documentation)
      # 匹配 'docs'
      commits:
        - pattern: '^docs'

    - title: 🚧 其他提交 (Other Commits)
      # 捕获所有未被以上分类匹配，且未被排除的提交。
      commits:
        - pattern: '*'